image: openjdk8:8-jdk
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - .gradle/build-cache/
build:
  script:
    - ./gradlew build

